name: Functional Tests
on: 
  workflow_dispatch:
    inputs:
      api_base_url:
        description: 'API Base URL'
        required: true
      api_key:
        description: 'API Key'
        required: true
        type: secret
      model_name:
        description: 'Model Name'
        required: true
  push:
    branches: [ main ]
    paths:
      - 'tests/test_*.py'
      - 'src/**'
      - 'database/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'tests/test_*.py'
      - 'src/**'
      - 'database/**'

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    
    env:
      PYTHONPATH: ${{ github.workspace }}
      DATABASE_URL: sqlite:///database/llm_evaluation.db
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Initialize test database
        run: |
          python database/init_db.py
          
      - name: Run functional tests
        env:
          API_BASE_URL: ${{ inputs.api_base_url }}
          API_KEY: ${{ inputs.api_key }}
          MODEL_NAME: ${{ inputs.model_name }}
          DATABASE_URL: sqlite:///database/llm_evaluation.db
          PROVIDER_TYPE: off_prem_api
          PROVIDER_NAME: TestProvider
          MODEL_TYPE: text-generation
          MODEL_ARCHITECTURE: transformer
        run: |
          # Run only functional unit tests
          pytest -v \
            tests/test_db_persistence.py \
            tests/test_execution_flow.py \
            tests/test_initial_data.py \
            tests/test_initialization.py \
            tests/test_model_registration.py \
            tests/test_schema_state.py \
            tests/test_simple.py \
            --junitxml=test-results/functional-tests.xml
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: functional-test-results
          path: test-results/functional-tests.xml
